// <auto-generated />
using System;
using InfoTemTuiFly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfoTemTuiFly.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190210105237_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("InfoTemTuiFly.Models.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GpsCoords");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("InfoTemTuiFly.Models.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DeparatureId");

                    b.Property<int?>("DestinationId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DeparatureId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("InfoTemTuiFly.Models.Entities.Flight", b =>
                {
                    b.HasOne("InfoTemTuiFly.Models.Entities.Airport", "Deparature")
                        .WithMany()
                        .HasForeignKey("DeparatureId");

                    b.HasOne("InfoTemTuiFly.Models.Entities.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");
                });
#pragma warning restore 612, 618
        }
    }
}
